baseURL = 'https://richardasante.com'
languageCode = 'en-us'
title = 'Memento'
theme = ["ananke","hugo-shortcode-gallery"]
Paginate = 4
SectionPagesMenu = "main"

[params]
copyright = "Richard Asante"
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Biography of Pharm Richard Asante."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-navy"
#cover_dimming_class = "bg-navy-60"
#recent_posts_number = 0
disable_share = true

[params.content.paragraphs]
style="text-align: justify"
