baseURL = '/'
languageCode = 'en-us'
title = 'Memento'
theme = ["ananke","hugo-shortcode-gallery"]


Paginate = 1


[params]
SectionPagesMenu = "main"
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Biography of Pharm Richard Asante."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-navy"
#recent_posts_number = 3
